---
- name: testing ubuntu file
  hosts: localhost
  tasks:
    - name: test version of ubuntu
      command: date
      register: date_output
    - name: priting date
      debug:
        msg: "{{ date_output }}"
